# Global configurations
global:
  namespace: cogni-dispatch
  imageRegistry: cogniregistry.azurecr.io
  imagePullPolicy: Always
  imageTag: latest

# Microservices Configurations
nginx:
  enabled: true
  replicas: 2
  image: cogni-nginx
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

authService:
  enabled: true
  replicas: 2
  image: cogni-auth-service
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

vendorService:
  enabled: true
  replicas: 2
  image: cogni-vendor-service
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

aiService:
  enabled: true
  replicas: 2
  image: cogni-ai-service
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

adminService:
  enabled: true
  replicas: 2
  image: cogni-admin-service
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

dispatchService:
  enabled: true
  replicas: 2
  image: cogni-dispatch-service
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

paymentService:
  enabled: true
  replicas: 2
  image: cogni-payment-service
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

frontend:
  enabled: true
  replicas: 2
  image: cogni-frontend
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Application Settings
config:
  nodeEnv: production
  mongodbUri: "mongodb://cosmos-cognidispatch-db:<password>@cosmos-cognidispatch-db.mongo.cosmos.azure.com:10255/cognidispatch?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@cosmos-cognidispatch-db@"
  azureSpeechKey: "REPLACE_WITH_YOUR_KEY"
  azureSpeechRegion: "centralindia"
  azureOpenaiEndpoint: "https://mock-openai.openai.azure.com/"
  azureOpenaiKey: "mock_openai_key"
  azureOpenaiDeployment: "gpt-4o"
  allowedClientIp: "http://20.207.99.48"
  openaiApiKey: "mock_openai_api_key"

# Managed Key Vault Secrets Mount Configuration (Set true in Production)
keyvault:
  enabled: false
  name: "kv-cogni-prod-589"
  tenantId: "YOUR_AZURE_TENANT_ID"
  clientId: "YOUR_USER_ASSIGNED_IDENTITY_CLIENT_ID"
  workloadIdentityEnabled: false

# Ingress Controller Configuration
ingress:
  enabled: false
  className: "addon-http-application-routing"
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
  hosts:
    - host: cognidispatch.local
      paths:
        - path: /
          pathType: Prefix
