{{- if .Values.keyvault.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cogni-secrets-provider
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.keyvault.clientId | quote }}
    keyvaultName: {{ .Values.keyvault.name | quote }}
    cloudName: ""
    objects: |
      array:
        - |
          objectName: MONGODB-URI
          objectType: secret
        - |
          objectName: AZURE-OPENAI-KEY
          objectType: secret
        - |
          objectName: AZURE-SPEECH-KEY
          objectType: secret
        - |
          objectName: JWT-SECRET
          objectType: secret
    tenantId: {{ .Values.keyvault.tenantId | quote }}
{{- end -}}
