apiVersion: v1
kind: Service
metadata:
  name: cogni-frontend-svc
  namespace: cogni-dispatch
  labels:
    app: cogni-frontend
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: cogni-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
