apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cognidispatch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/gokulk18/CogniDispatch.git"
    targetRevision: "main"
    path: "helm/cognidispatch"
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "cogni-dispatch"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
