name: Auth_Service_CI

on:
  push:
    branches:
      - main
    paths:
      - 'services/auth-service/**'
      - 'services/shared/**'
      - '.github/workflows/auth-service.yml'
  workflow_dispatch:

jobs:
  call-common-ci:
    uses: ./.github/workflows/common-ci.yml
    with:
      working_directory: services/auth-service
      image_name: cogni-auth-service
      service_name: auth-service
      dockerfile_path: services/Dockerfile
      docker_build_context: services
      sonar_project_key: cogni-auth-service
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
